apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 5m
  releaseName: my-nats
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 1m
