apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: project-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/ptuomola/kubernetes
  ref:
    branch: master
